### ISSUE TITLE
Possibility of inclusion in the LifeMC modpack of the LifeMC Studios team

### ISSUE THREAD

**Issue by Nukecraft5419** [AndyRusso/pvplegacyutils#2]
Hello we at LifeMC Studios are considering including this mod in our modpack, our modpack is on 3 versions 1.18.2, 1.19.4, 1.20.1 and it all runs on fabric we noticed that your mod is currently not for 1.18.2, and we would like to ask if it is possible to backport it to 1.18.2 and then have a list of incompatibilities to see if it will give problems with other mods in the modpack, the modpack is almost out we hope to include it before the release

**Comment by AndyRusso** [comment]
Hello! I'm glad to hear that. However, I am not interested in supporting 1.18.2. Thank you for your offer, though.

**Comment by Nukecraft5419** [comment]
Thank you anyway, in case you change your mind we will be ready to put this mod into our modpack after due testing
